### ISSUE TITLE
Still buggy

### ISSUE THREAD

**Issue by saspol** [alextaujenis/RBD_Light#5]
``` arduino
void loop() {
  backlight_left.update();
  backlight_right.update();

  if ( button1.isPressed() ) {
    backlight_left.setBrightness(255);
    backlight_right.setBrightness(255);
  }
  if ( button1.onPressed() ) {
    Serial.println("PRESSED");
  }
  if (button1.onReleased() ) {
    Serial.println("RELEASED");
    backlight_left.setBrightness(0);
    backlight_right.setBrightness(0);
    Serial.print(backlight_left.getBrightness());
    Serial.print(" ");
    Serial.println(backlight_right.getBrightness());
  }
```

What we see in console:

```
**** Start ****
RELEASED
0 0
PRESSED
RELEASED
0 0
PRESSED
RELEASED
0 0
PRESSED
RELEASED
0 0
PRESSED
RELEASED
0 0
PRESSED
RELEASED
0 0
PRESSED
RELEASED
0 0
```

What really happens:
After button release backlight_left, backlight_left still on randomly even getBrightness() return 0!
If i use just analogWrite, everything working fine.
Im curious, did you test your "library" even 15min?

**Comment by alextaujenis** [comment]
> Im curious, did you test your "library" even 15min?

I spent several hours today [investigating your previous issue](https://github.com/alextaujenis/RBD_Light/issues/4), improving the [unit tests](https://github.com/alextaujenis/RBD_Light/blob/master/extras/unit_test/unit_test.ino), writing a bug fix that doesn't change the expected behavior or break any of the existing tests, documenting the changes, then compressing, tagging, and pushing the release.

This library is backed by 63 unit tests that make sure it behaves correctly. Here's the test I wrote just for you today:

``` arduino
// GitHub issue #4 bug fix
// https://github.com/alextaujenis/RBD_Light/issues/4
  test(blink_should_turn_on_the_light_after_calling_setBrightness) {
    light.setBrightness(128);
    light.blink(100,100);
    light.update();
    assertTrue(isOn());
    testCleanup();
  }
```

I also did a sanity check by writing a test script and checking the output in the serial monitor... So to answer your question if I even tested this library: Yes, and it's backed by 650 lines of unit tests.

The way you asked me if I even tested my library sounds like you are trying to be mean. You are using libraries that took months to build and that I released solely for your benefit, for free. Be nice. Most people (or projects) don't patch a bug less than 4 hours after it was reported.

My advice to you (or your group) is that you may be having debounce issues because button1.isPressed() is not debounced (only onPressed() is debounced). This could trigger the lights turning on randomly. You should move the Serial.print(light.getBrightness()); calls outside of the 'if' statement into the normal loop. This way you can see when the brightness actually changes. Also, you can just call light.on() or light.off() instead of setBrightness(255) or setBrightness(0).

**Comment by saspol** [comment]
Hi, i respect your work but im sure is still some bug there.
The problem in combination blink with light.on/off and maybe setBrightness.
Button part work like charm.
In this code on button press lights blink 3 times, then stay on until button released.
The issue is same - onReleased condition starts, but .off() work randomly, lights still stay on sometimes.
Just replace light.off with analogWrite(PIN, 0) solves the problem 100%.

``` arduino
setup () {
  timer.setTimeout((30 + 30) * 3);
}
void loop() {
  backlight_left.update();
  backlight_right.update();

  if ( brake.onPressed() ) {
    timer.restart();
    backlight_left.blink(30, 30, 3);
    backlight_right.blink(30, 30, 3);

  }

  if ( brake.isPressed() && timer.isExpired() ) {
    backlight_left.on();
    backlight_right.on(); 
  }

  if (brake.onReleased() ) {
    backlight_left.off();
    backlight_right.off();
  }
}
```

**Comment by alextaujenis** [comment]
## Arduino Flickering Vehicle (Car) Brake Lights

![Arduino Vehicle Brake Light Example](http://i.imgur.com/GcZZhvg.gif)

Blink a light 3 times on button press, stay on until button release. This is expected behavior of vehicle brake lights that flicker to get your attention. This is tested and working with [RBD::Light v2.1.6](https://github.com/alextaujenis/RBD_Light/releases/tag/2.1.6).

``` arduino

#include <RBD_Timer.h>  // https://github.com/alextaujenis/RBD_Timer
#include <RBD_Button.h> // https://github.com/alextaujenis/RBD_Button
#include <RBD_Light.h>  // https://github.com/alextaujenis/RBD_Light

#define LENGTH 30 // on/off length of blink in ms
#define COUNT 3   // number of blinks

RBD::Button button(2); // button connected to digital pin 2 and ground
RBD::Light  light(13); // built-in arduino led
RBD::Timer  timer(2*LENGTH*COUNT); // blink timer

void setup() {}

void loop() {
  light.update();

  // blink the light 3 times when the button is pressed
  if(button.onPressed()) {
    light.blink(LENGTH,LENGTH,COUNT);
    timer.restart();
  }

  // turn on the light when it is finished blinking, only if the button is still pressed
  if(timer.onExpired() && button.isPressed()) {
    light.on();
  }

  // turn off the light when the button is released
  if(button.onReleased()) {
    light.off();
  }
}
```

**Comment by saspol** [comment]
Thanx, you code is working as expected. Dont know why my not ;)
I also find when use button.InvertReading() the button.OnRelease() is
always true during program start.
This is looks like wrong behavour.
Just try replace in your code

  if(button.onReleased()) {
    light.off();
  }

 with "fadeout":

  if (button.onReleased()) {
        light.fade(0, 0, 200, 0, 0);
  }

Mitry

2016-03-02 0:56 GMT+05:30 Alex Taujenis notifications@github.com:

**Comment by alextaujenis** [comment]
> I also find when use button.InvertReading() the button.OnRelease() is always true during program start.

This is the expected behavior. With your Normally Closed button; the Arduino boots up with the button in the "released" state, so the library behaves accordingly.

> This is looks like wrong behavour... with "fadeout":

``` arduino
if (button.onReleased()) {
  light.fade(0, 0, 200, 0, 0);
}
```

I understand that the light fades out when the Arduino boots up, but that's not what looks wrong with this code. You should pass in 1 [times] to the fade function instead of 0:

``` arduino
if (button.onReleased()) {
  light.fade(0, 0, 200, 0, 1);
}
```

Your code that passes 0 into the fade [times] works right now but I realize it's a bug in [RBD::Light](https://github.com/alextaujenis/RBD_Light) and I'm going to patch it today.

So to summarize everything here with an answer: You should use a boolean value to stop the button.onReleased() event from firing when the Arduino boots up. Copy this Arduino sketch below and uncomment button.invertReading() in the setup().

``` arduino
#include <RBD_Timer.h>  // https://github.com/alextaujenis/RBD_Timer
#include <RBD_Button.h> // https://github.com/alextaujenis/RBD_Button
#include <RBD_Light.h>  // https://github.com/alextaujenis/RBD_Light

#define LENGTH 30 // on/off length of blink in ms
#define COUNT 3   // number of blinks

RBD::Button button(2); // button connected to digital pin 2 and ground
RBD::Light  light(13); // built-in arduino led
RBD::Timer  timer(2*LENGTH*COUNT); // blink timer

bool skip_first_run = true;

void setup() {
  // button.invertReading();
}

void loop() {
  light.update();

  // blink the light 3 times when the button is pressed
  if(button.onPressed()) {
    light.blink(LENGTH,LENGTH,COUNT);
    timer.restart();
  }

  // turn on the light when it is finished blinking, only if the button is still pressed
  if(timer.onExpired() && button.isPressed()) {
    light.on();
  }

  // fade out the light when the button is released
  if(button.onReleased()) {
    if(!skip_first_run) {
      light.fade(0,0,200,0,1);
    }
    skip_first_run = false;
  }
}
```

**Comment by saspol** [comment]
Boolean check of start i already did, but what i think - onRelease must not
return true on boot because nothing been pressed.

**Comment by alextaujenis** [comment]
> onRelease must not return true on boot because nothing been pressed.

You do not need to call button.invertReading() unless you have a Normally Closed button.

Connect your button to Arduino digital pin 2 and ground, make sure it is released, then run this sketch and tell me what prints to the Serial Monitor.

``` arduino
#include <RBD_Timer.h>  // https://github.com/alextaujenis/RBD_Timer
#include <RBD_Button.h> // https://github.com/alextaujenis/RBD_Button

RBD::Button button(2);

void setup() {
  Serial.begin(115200);
  while(!Serial);
}

void loop() {
  if(button.onPressed()) {
    Serial.println("Button Pressed");
  }

  if(button.onReleased()) {
    Serial.println("Button Released");
  }
}
```

**Comment by saspol** [comment]
Some more strange behavour.
With construction like this i expect fadeout start from someBrightness.
Instead of this it start from maximum.

```
  light.setBrightness(someBrightness);
  light.fade(0,0,3000,0,1);
```

Can you please add to light.fade two arguments with maximumBrightness and
minimumBrightness? It will help a lot and make code less messy.

Mitry

2016-03-08 0:40 GMT+05:30 Alex Taujenis notifications@github.com:
